package org.kurento.room;

/**
 * Credentials for TURN generated by ITurnProvider implementations.
 */
public class TurnKMSCredentials {
    private String stunUrl;
    private int stunPort;
    private String turnUrl;

    public String getStunUrl() {
        return stunUrl;
    }

    public void setStunUrl(String stunUrl) {
        this.stunUrl = stunUrl;
    }

    public int getStunPort() {
        return stunPort;
    }

    public void setStunPort(int stunPort) {
        this.stunPort = stunPort;
    }

    public String getTurnUrl() {
        return turnUrl;
    }

    public void setTurnUrl(String turnUrl) {
        this.turnUrl = turnUrl;
    }

    @Override
    public String toString() {
        return "TurnKMSCredentials{" +
                "stunUrl='" + stunUrl + '\'' +
                ", stunPort=" + stunPort +
                ", turnUrl='" + turnUrl + '\'' +
                '}';
    }
}
